import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parent.parent))

import numpy as np
import streamlit as st
from core.minimover_fk import compute
from core.minimover_ik import solve_full, UnreachableTarget

st.set_page_config(page_title="MINIMOVER Inverse Kinematics", page_icon="🎯", layout="wide")
st.title("🎯 MINIMOVER Inverse Kinematics")

st.markdown(
    "Solve for the 5 joint angles that reach a target position and "
    "orientation. Like the 2-DoF case, this generally has more than one "
    "solution."
)

mode = st.radio(
    "How do you want to set the target?",
    ["Generate from known joint angles (round-trip check)", "Enter a custom target"],
)

col1, col2 = st.columns(2)
l1 = col1.number_input("L1", min_value=0.01, value=2.0)
l2 = col2.number_input("L2", min_value=0.01, value=1.5)

if mode == "Generate from known joint angles (round-trip check)":
    cols = st.columns(5)
    thetas_deg = [cols[i].number_input(f"true theta{i+1} (deg)", value=[25, 35, -20, 15, 55][i], key=f"tt_{i}") for i in range(5)]
    thetas = [np.deg2rad(t) for t in thetas_deg]
    t_final, _ = compute(l1, l2, thetas)
    qx, qy, qz = t_final[:3, 3]
    r = t_final[:3, :3]
    st.caption(f"Target generated by forward kinematics: ({qx:.4f}, {qy:.4f}, {qz:.4f})")
else:
    col3, col4, col5 = st.columns(3)
    qx = col3.number_input("Target x", value=2.0)
    qy = col4.number_input("Target y", value=1.0)
    qz = col5.number_input("Target z", value=-1.0)
    st.caption("Enter the target orientation matrix (top-left 3x3 of T_5_0).")
    r = np.eye(3)
    for i in range(3):
        cols = st.columns(3)
        for j in range(3):
            r[i, j] = cols[j].number_input(f"r[{i+1}][{j+1}]", value=float(np.eye(3)[i, j]), key=f"ik_r_{i}_{j}")

st.divider()

try:
    solutions = solve_full(l1, l2, qx, qy, qz, r)
except UnreachableTarget as e:
    st.error(str(e))
else:
    for theta1, theta2, theta3, theta4, theta5, label in solutions:
        st.subheader(label)
        cols = st.columns(5)
        for i, (name, val) in enumerate(zip(
            ["theta1", "theta2", "theta3", "theta4", "theta5"],
            [theta1, theta2, theta3, theta4, theta5],
        )):
            cols[i].metric(name, f"{np.rad2deg(val):.2f} deg")

        check_final, _ = compute(l1, l2, [theta1, theta2, theta3, theta4, theta5])
        reached = check_final[:3, 3]
        st.caption(
            f"Forward kinematics check: these angles reach "
            f"({reached[0]:.4f}, {reached[1]:.4f}, {reached[2]:.4f})."
        )
